# Generated by Django 2.0.2 on 2018-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reg_code',
            field=models.CharField(default=1234, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'admin')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together={('user', 'company')},
        ),
    ]
